### ISSUE TITLE
THANK YOU THANK YOU THANK YOU for this plugin!!!

### ISSUE THREAD

**Issue by jclarke0000** [Danimal4326/homebridge-ecoplug#1]
Since one can no longer send private messages on GitHub, I'm opening an "issue" to say thank you for this plugin.  I was about to replace my ECO Plug with something that natively supports HomeKit, then I came across this!  It was the last piece of my puzzle... now I can control my entire smart home -- inside and out -- with Siri.

Feel free to close this :)

 - Jeff

**Comment by Danimal4326** [comment]
Thanks!
