### ISSUE TITLE
ecoplug and geekbe

### ISSUE THREAD

**Issue by ldhall1856** [Danimal4326/homebridge-ecoplug#11]
Hi 

First off thank you so much for what you have done with ecoplug. 

I was wondering if there is anyway to make the plugin work with [Geekbes smart plug](https://www.amazon.com/Geekbes-Socket-Compatible-Control-Android/dp/B073Z895LR/ref=sr_1_3?ie=UTF8&qid=1521428559&sr=8-3&keywords=geekbes+smart+plugs)

They are the same product and run the same iphone app(Smart Life).

I'm very new at writing and reading code but am trying to learn. It could be i didn't set up my plugs correctly.  Any help would be appreciate.

Thanks!

**Comment by Danimal4326** [comment]
Eco plugs use the  "Eco plugs" app.   If they use the same protocol, the plugin should just work if you set it up correctly.  Else, without having the Geekbes plug, I can't tell what the protocol is..

**Comment by ldhall1856** [comment]
Sorry,  I was incorrect.... Thanks for your quick reply
